
services:
  postgres:
    image: postgres:13
    ports:
      - "5433:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - ./.env
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    env_file:
      - ./.env
    depends_on:
      - postgres

  mysql:
    image: mysql:5
    env_file:
      - ./.env
    ports:
    - "33061:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./.env
    ports:
      - "8080:80"
    depends_on:
      - mysql